### ISSUE TITLE
New deal notification showing the same price twice

### ISSUE THREAD

**Issue by psuzn** [psuzn/Play-Deals-Backend#51]
![image](https://github.com/psuzn/Play-Deals-Backend/assets/19205305/0c3f075d-8759-4e03-8f53-e6cd8043204c)

**Comment by psuzn** [comment]
Again, thank you @Zaxx69. This should be fixed with the deployment of [v2.2.3](https://github.com/psuzn/Play-Deals-Backend/actions/runs/7519255658)

**Comment by Zaxx69** [comment]
Thank you for fixing it
